# Generated by Django 4.1.1 on 2022-10-12 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FullReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewText', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servedDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eggs', models.BooleanField()),
                ('fish', models.BooleanField()),
                ('gluten', models.BooleanField()),
                ('milk', models.BooleanField()),
                ('peanuts', models.BooleanField()),
                ('shellfish', models.BooleanField()),
                ('soy', models.BooleanField()),
                ('treeNuts', models.BooleanField()),
                ('vegan', models.BooleanField()),
                ('vegetarian', models.BooleanField()),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemDietServed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meal')),
                ('menuItemDiet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menuitemdiet')),
            ],
        ),
        migrations.CreateModel(
            name='Servery',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewText', models.CharField(max_length=200)),
                ('complete', models.BooleanField()),
                ('rating', models.IntegerField()),
                ('fullReview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fullreview')),
                ('menuItemDietServed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menuitemdietserved')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('netid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30)),
                ('numreviews', models.IntegerField(default=0)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.college')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='mealType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mealtype'),
        ),
        migrations.AddField(
            model_name='meal',
            name='servery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servery'),
        ),
        migrations.AddField(
            model_name='fullreview',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meal'),
        ),
        migrations.AddField(
            model_name='fullreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reviewer'),
        ),
        migrations.AddConstraint(
            model_name='reviewitem',
            constraint=models.UniqueConstraint(fields=('fullReview', 'menuItemDietServed'), name='unique review, menuItemDietServed'),
        ),
        migrations.AddConstraint(
            model_name='menuitemdietserved',
            constraint=models.UniqueConstraint(fields=('menuItemDiet', 'meal'), name='menu item constraint'),
        ),
        migrations.AddConstraint(
            model_name='menuitemdiet',
            constraint=models.UniqueConstraint(fields=('menuItem', 'eggs', 'fish', 'gluten', 'milk', 'peanuts', 'shellfish', 'soy', 'treeNuts', 'vegan', 'vegetarian'), name='menuItemDiet constraint'),
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('servery', 'mealType', 'servedDate'), name='meal constraint'),
        ),
        migrations.AddConstraint(
            model_name='fullreview',
            constraint=models.UniqueConstraint(fields=('reviewer', 'meal'), name='unique reviewer, meal'),
        ),
    ]
