# Generated by Django 4.1.1 on 2022-09-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vegetarian', models.BooleanField()),
                ('glutenFree', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemServed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('college', models.CharField(max_length=20)),
                ('numreviews', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='fullreview',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reviewitem',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='reviewitem',
            name='fullReview',
        ),
        migrations.RemoveField(
            model_name='reviewitem',
            name='text',
        ),
    ]
