# Generated by Django 4.1.1 on 2022-10-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='menuitemdietserved',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
