# Generated by Django 4.1.1 on 2022-10-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_test_menuitemdietserved_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemdietserved',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
