# Generated by Django 4.1.1 on 2022-09-25 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_meal_mealtype_menuitem_menuitemserved_reviewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='mealType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mealtype'),
        ),
        migrations.AddField(
            model_name='meal',
            name='servedDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='servery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.servery'),
        ),
    ]
