# Generated by Django 4.1.1 on 2022-09-25 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_meal_mealtype_meal_serveddate_meal_servery'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullreview',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.meal'),
        ),
        migrations.AddField(
            model_name='fullreview',
            name='reviewText',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='fullreview',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.reviewer'),
        ),
        migrations.AddField(
            model_name='menuitemserved',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.meal'),
        ),
        migrations.AddField(
            model_name='menuitemserved',
            name='menuItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.menuitem'),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='complete',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='fullReview',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.fullreview'),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='menuItemServed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.menuitemserved'),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reviewitem',
            name='reviewText',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
