# Generated by Django 4.1.1 on 2022-11-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_menuitemdietserved_rating_menuitemdietrating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemdietrating',
            name='numReviews',
            field=models.IntegerField(default=0),
        ),
    ]
