# Generated by Django 4.1.1 on 2022-09-25 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fullreview_meal_fullreview_reviewtext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullreview',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meal'),
        ),
        migrations.AlterField(
            model_name='fullreview',
            name='reviewText',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='fullreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.reviewer'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='mealType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mealtype'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='servedDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='servery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.servery'),
        ),
        migrations.AlterField(
            model_name='menuitemserved',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.meal'),
        ),
        migrations.AlterField(
            model_name='menuitemserved',
            name='menuItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menuitem'),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='complete',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='fullReview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fullreview'),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='menuItemServed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.menuitemserved'),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reviewitem',
            name='reviewText',
            field=models.CharField(max_length=200),
        ),
    ]
