# Generated by Django 4.1.1 on 2022-09-28 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_fullreview_meal_alter_fullreview_reviewtext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='mealtype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='servery',
            name='id',
        ),
        migrations.AlterField(
            model_name='mealtype',
            name='name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='netid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='numreviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servery',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='fullreview',
            constraint=models.UniqueConstraint(fields=('reviewer', 'meal'), name='unique reviewer, meal'),
        ),
        migrations.AddConstraint(
            model_name='meal',
            constraint=models.UniqueConstraint(fields=('servery', 'mealType', 'servedDate'), name='meal constraint'),
        ),
        migrations.AddConstraint(
            model_name='menuitemserved',
            constraint=models.UniqueConstraint(fields=('menuItem', 'meal'), name='menu item constraint'),
        ),
        migrations.AddConstraint(
            model_name='reviewitem',
            constraint=models.UniqueConstraint(fields=('fullReview', 'menuItemServed'), name='unique review, menuItemServed'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.college'),
        ),
    ]
