# Generated by Django 4.1.1 on 2022-09-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_college_remove_mealtype_id_remove_menuitem_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='id',
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='college',
            field=models.CharField(max_length=20),
        ),
    ]
