# Generated by Django 4.1.1 on 2022-09-28 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_college_id_alter_college_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.college'),
        ),
    ]
