# Generated by Django 4.1.1 on 2022-09-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_reviewer_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='glutenFree',
            new_name='gluten',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='eggs',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='fish',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='milk',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='peanuts',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='shellfish',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='soy',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='treeNuts',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='vegan',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
