# Generated by Django 4.1.1 on 2022-09-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_glutenfree_menuitem_gluten_menuitem_eggs_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('name', 'eggs', 'fish', 'gluten', 'milk', 'peanuts', 'shellfish', 'soy', 'treeNuts', 'vegan', 'vegetarian'), name='menuItem constraint'),
        ),
    ]
